
services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    working_dir: /usr/workspace
    environment:
      - STAGE=prod
    command: /bin/sh -c "ls -la && pytest -sv --alluredir=allure-results"


