version: '3.7'

services:
  run_tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    working_dir: /usr/workspace
    environment:
      - STAGE=prod
    command: /bin/sh -c "pytest -sv -n=4 --alluredir=allure-results"

  report:
    depends_on:
      - run_tests
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/workspace
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "allure generate allure-results --clean -o allure-report"