name: CI

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:

env:
  STAGE: prod

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Checkout (copy) gh-pages repository to GitHub runner
#        uses: actions/checkout@v2
#        with:
#          ref: gh-pages
#          path: ./.github/gh-pages

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Run tests
        run: pytest --alluredir=allure-results || true

#      - name: Copy history from gh-pages to allure-results
#        run: |
#          sudo mkdir -p allure-results/history
#          sudo cp -R ./.github/gh-pages/history/* allure-results/history/

#      - name: Get Allure history
#        uses: actions/checkout@v3
#        if: always()
#        with:
#          ref: gh-pages
#          path: gh-pages
#
#      - name: Allure Report action from marketplace
#        uses: simple-elf/allure-report-action@v1.7
#        if: always()
#        with:
#          allure_results: allure-results
#          allure_history: allure-history
#          gh_pages: gh_pages
#
#      - name: Deploy report to Github Pages
#        if: always()
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.CI_TOKEN }}
#          publish_branch: gh-pages
#          publish_dir: allure-history
      - name: Install Allure
        run: |
          apt-get update && apt-get install -y openjdk-17-jre openjdk-17-jdk
          wget https://github.com/allure-framework/allure2/releases/download/2.26.0/allure-2.26.0.tgz 
          tar -zxvf allure-2.26.0.tgz -C /opt/ 
          sudo ln -s /opt/allure-2.26.0/bin/allure /usr/bin/allure

      - name: Generate Allure report
        run: allure generate allure-results --clean -o allure-report

#      - name: Update Allure history
#        run: |
#          sudo cp -R allure-report/history/* ./.github/gh-pages/history/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true
