name: CI

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'prod'
        type: choice
        options:
          - prod
          - dev

env:
  STAGE: ${{ github.event.inputs.environment }}

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get install -y docker-compose

      - name: Run tests via Docker-compose
        run: docker-compose up --exit-code-from tests || true

      - name: Generate Allure report
        run: docker-compose up tests /bin/bash -c "allure generate allure-results --clean -o allure-report"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true
