name: CI

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'prod'
        type: choice
        options:
          - prod
          - dev
      browser:
        description: 'Select browser'
        required: true
        default: 'chromium'
        type: choice
        options:
          - chromium
          - firefox

env:
  STAGE: ${{ github.event.inputs.environment }}

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Install Allure
        run: |
          apt-get update && apt-get install -y openjdk-17-jre openjdk-17-jdk wget 
          wget https://github.com/allure-framework/allure2/releases/download/2.26.0/allure-2.26.0.tgz
          tar -zxvf allure-2.26.0.tgz -C /opt/  
          sudo ln -s /opt/allure-2.26.0/bin/allure /usr/bin/allure

      - name: Run tests
        run: pytest --browser=${{ github.event.inputs.browser }} -sv --alluredir=allure-results -n=4 || true

      - name: Generate Allure report
        run: allure generate allure-results --clean -o allure-report

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true
